//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystAnalys_lr1.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystAnalys_lr1.Strings.MainStrings", typeof(MainStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Через путь.
        /// </summary>
        internal static string acrossThePath {
            get {
                return ResourceManager.GetString("acrossThePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на После.
        /// </summary>
        internal static string AfterButton {
            get {
                return ResourceManager.GetString("AfterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднее:.
        /// </summary>
        internal static string average {
            get {
                return ResourceManager.GetString("average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должно быть больше 2 ребер.
        /// </summary>
        internal static string bus {
            get {
                return ResourceManager.GetString("bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановки.
        /// </summary>
        internal static string busStops {
            get {
                return ResourceManager.GetString("busStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на График.
        /// </summary>
        internal static string chart {
            get {
                return ResourceManager.GetString("chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите другой путь для конфигурации.
        /// </summary>
        internal static string chooseWay {
            get {
                return ResourceManager.GetString("chooseWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить все:.
        /// </summary>
        internal static string clearAll {
            get {
                return ResourceManager.GetString("clearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите очистить граф/маршрут/светофоры/остановки?.
        /// </summary>
        internal static string clearGraph {
            get {
                return ResourceManager.GetString("clearGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация:.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во автобусов.
        /// </summary>
        internal static string countBuses {
            get {
                return ResourceManager.GetString("countBuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во датчиков.
        /// </summary>
        internal static string countSensors {
            get {
                return ResourceManager.GetString("countSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цикл.
        /// </summary>
        internal static string cycle {
            get {
                return ResourceManager.GetString("cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить все автобусы маршрута/сети?.
        /// </summary>
        internal static string deleteBus {
            get {
                return ResourceManager.GetString("deleteBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить граф/маршрут? .
        /// </summary>
        internal static string deleteGraph {
            get {
                return ResourceManager.GetString("deleteGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При T равном.
        /// </summary>
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный путь к файлу.
        /// </summary>
        internal static string errorPath {
            get {
                return ResourceManager.GetString("errorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено.
        /// </summary>
        internal static string found {
            get {
                return ResourceManager.GetString("found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маршрут/граф.
        /// </summary>
        internal static string graphClear {
            get {
                return ResourceManager.GetString("graphClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезагрузите программу для смены языка.
        /// </summary>
        internal static string hint {
            get {
                return ResourceManager.GetString("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания матрицы.
        /// </summary>
        internal static string Matrix {
            get {
                return ResourceManager.GetString("Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С датчиками:.
        /// </summary>
        internal static string matrixFirst {
            get {
                return ResourceManager.GetString("matrixFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без:.
        /// </summary>
        internal static string matrixSecond {
            get {
                return ResourceManager.GetString("matrixSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего:.
        /// </summary>
        internal static string matrixThird {
            get {
                return ResourceManager.GetString("matrixThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мин.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сеть.
        /// </summary>
        internal static string network {
            get {
                return ResourceManager.GetString("network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ничего.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В папке отсутствует изображение.
        /// </summary>
        internal static string noPic {
            get {
                return ResourceManager.GetString("noPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено.
        /// </summary>
        internal static string notFound {
            get {
                return ResourceManager.GetString("notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во итераций.
        /// </summary>
        internal static string numIter {
            get {
                return ResourceManager.GetString("numIter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры загрязнения.
        /// </summary>
        internal static string ParametresLabel {
            get {
                return ResourceManager.GetString("ParametresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процент неудач:.
        /// </summary>
        internal static string procentFailed {
            get {
                return ResourceManager.GetString("procentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процент успеха:.
        /// </summary>
        internal static string procentSuc {
            get {
                return ResourceManager.GetString("procentSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (1)Осталось поставить светофоров.
        /// </summary>
        internal static string putTrafficLights1 {
            get {
                return ResourceManager.GetString("putTrafficLights1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (2)Осталось поставить светофоров.
        /// </summary>
        internal static string putTrafficLights2 {
            get {
                return ResourceManager.GetString("putTrafficLights2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет.
        /// </summary>
        internal static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение....
        /// </summary>
        internal static string saving {
            get {
                return ResourceManager.GetString("saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сек.
        /// </summary>
        internal static string sec {
            get {
                return ResourceManager.GetString("sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снижение кол-ва датчиков в процентах.
        /// </summary>
        internal static string sensorsDown {
            get {
                return ResourceManager.GetString("sensorsDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настроить.
        /// </summary>
        internal static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До изменений .
        /// </summary>
        internal static string ShowOriginalButton {
            get {
                return ResourceManager.GetString("ShowOriginalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать результат.
        /// </summary>
        internal static string ShowResultLabel {
            get {
                return ResourceManager.GetString("ShowResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Симуляция.
        /// </summary>
        internal static string SimulationLaabel {
            get {
                return ResourceManager.GetString("SimulationLaabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить/Остановить.
        /// </summary>
        internal static string StartStopLabel {
            get {
                return ResourceManager.GetString("StartStopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станции.
        /// </summary>
        internal static string station {
            get {
                return ResourceManager.GetString("station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автобусы.
        /// </summary>
        internal static string theBuses {
            get {
                return ResourceManager.GetString("theBuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Времени прошло : .
        /// </summary>
        internal static string TimePastLabel {
            get {
                return ResourceManager.GetString("TimePastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светофоры.
        /// </summary>
        internal static string TrafficLights {
            get {
                return ResourceManager.GetString("TrafficLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вершины и ребра.
        /// </summary>
        internal static string VandE {
            get {
                return ResourceManager.GetString("VandE", resourceCulture);
            }
        }
    }
}
